### ISSUE TITLE
Ligatures don't seem to export properly

### ISSUE THREAD

**Issue by mia-entropy** [glyphr-studio/Glyphr-Studio-2#215] opened 2024-07-19 17:56 UTC
**Describe the bug & what the expected behavior should be:**

I'm working on my conlang's script font which is a "reverse abugida" (central vowel on which consonants attaches). In the editor "live preview" the ligatures works perfectly, but when exported to OTF they don't work in any software (tested in GIMP, LibreOffice, in HTML with CSS; all on Linux). Ligatures are used to offset the consonants to follow the script structure.

My font [eberban_glyphr.gs2](https://github.com/user-attachments/files/16315352/eberban_glyphr.txt)

**Steps to reproduce the bug:**

1. Open the file in Glyphr Studio
2. Export to OTF and install the font
3. Try to type ligatures in other software.

**Other notes & screenshots:**

String `plla` is rendered like so in the live preview:
![image](https://github.com/user-attachments/assets/b4ef2709-6fed-4cb3-968e-9e1b60f79451)
In LibreOffice it renders like so:
![image](https://github.com/user-attachments/assets/ed300f61-7d9a-419e-93c4-cef4fe57d518)

**Comment by mia-entropy** [comment] 2024-07-19 18:23
When exporting from the gs2 file on my Windows computer the ligatures work in LibreOffice. However the OTF file exported on Linux also don't have working ligatures when copied on Windows. It thus seem to be an issue when exporting to OTF on Linux (or more specific case) specifically.

Edit: I copied the font exported on my Windows computer over on my Linux one and the ligatures works too. So it's definitly the export process that have an issue.

**Comment by mattlag** [comment] 2024-07-24 16:02
Hello! This seems like a very interesting bug. I do not have access to a Linux machine for testing. I'm wondering if you can help me out - can you send me the two .otf files, the one exported from windows and the one exported from linux? I can open them with some advanced font tools to see if there are any differences, or if I can easily reverse-engineer / understand why they are being exported differently. You can post them here, or you could email them to mail@glyphrstudio.com

Might also help to know what browser you are using on windows / linux to do the exporting. 

Thanks for the bug report!

**Comment by jessepav** [comment] 2024-09-17 02:40
Just to lend a hand, since the reporter has gone silent, I opened the `.gs2` in Linux (Ubuntu 22.04, Chrome 128), exported an `.otf` file, and tested it in LibreOffice. The `plla` ligature seems to work fine.

[eberban-Regular.otf.zip](https://github.com/user-attachments/files/17022236/eberban-Regular.otf.zip)

![LibreOffice screenshot](https://github.com/user-attachments/assets/a275b7cb-ac85-41a0-922b-35a0158f2b99)

**Comment by mattlag** [comment] 2024-09-17 19:18
Thank you for testing this, @jessepav ! I'm fairly certain any issue would not be caused by the OS itself, but rather the browser being used to export. Chrome (should?) be the same across OSs. Is there another popular browser on Linux that isn't Chrome or Firefox? Maybe @mia-entropy was using that browser.

But it's good to know it works on Linux + Chrome. I may close this if we don't hear anything further. Thank you!

**Comment by mattlag** [comment] 2024-09-25 20:26
Closing as fixed. @mia-entropy if you have a specific instance that still isn't working, we can re-open this.

**Closed as completed by mattlag** 2024-09-25 20:26 UTC
Labels: user reported

**Comment by mia-entropy** [comment] 2024-10-05 13:18
Hi! Sorry for the absence of response, I didn't get any notifications :/
I just generated again the OTF file on Linux (PopOs + Firefox 128.0) and it works correctly, so I don't know what I did wrong before, or maybe it was fixed by other changes :)

**Comment by mattl-msft** [comment] 2024-10-05 21:57
No worries - thanks for letting us know!

**Comment by mattlag** [comment] 2024-10-05 21:57
No worries - thanks for letting me know!
